import { LinhaGPX } from "@/types/cadastro";

export const LINHAS_GPX: LinhaGPX[] = [
  {
    id: 1,
    nome: "Agua Azul",
    arquivo: "/gpx/01-Agua Azul.gpx",
    raioMetros: 1500,
  },
  {
    id: 2,
    nome: "Arauna 1",
    arquivo: "/gpx/02-Arauna 1.gpx",
    raioMetros: 1500,
  },
  {
    id: 3,
    nome: "Arauna 2",
    arquivo: "/gpx/03-Arauna 2.gpx",
    raioMetros: 1500,
  },
  {
    id: 4,
    nome: "Flor da Mata",
    arquivo: "/gpx/04-Flor da Mata.gpx",
    raioMetros: 1500,
  },
  {
    id: 5,
    nome: "Guimaraes",
    arquivo: "/gpx/05-Guimaraes.gpx",
    raioMetros: 1500,
  },
  {
    id: 6,
    nome: "Módulo IV",
    arquivo: "/gpx/06-Módulo IV.gpx",
    raioMetros: 1500,
  },
  { id: 7, nome: "Pacuri", arquivo: "/gpx/07-Pacuri.gpx", raioMetros: 1500 },
  {
    id: 8,
    nome: "Boa Esperança",
    arquivo: "/gpx/08-Boa Esperança.gpx",
    raioMetros: 1500,
  },
  {
    id: 9,
    nome: "Boca Fria",
    arquivo: "/gpx/09-Boca Fria.gpx",
    raioMetros: 1500,
  },
  {
    id: 10,
    nome: "Querencia",
    arquivo: "/gpx/10-Querencia.gpx",
    raioMetros: 1500,
  },
  { id: 11, nome: "Tabapuã", arquivo: "/gpx/11-Tabapuã.gpx", raioMetros: 1500 },
  {
    id: 12,
    nome: "Teles Pires",
    arquivo: "/gpx/12-Teles Pires.gpx",
    raioMetros: 1500,
  },
  {
    id: 13,
    nome: "Nova Conquista",
    arquivo: "/gpx/13-Nova-conquista.gpx",
    raioMetros: 1500,
  },
  {
    id: 14,
    nome: "Grota do Sapo",
    arquivo: "/gpx/14-Grota do Sapo.gpx",
    raioMetros: 1500,
  },
  {
    id: 15,
    nome: "Cinco Estrelas",
    arquivo: "/gpx/15-Cinco Estrelas.gpx",
    raioMetros: 1500,
  },
  { id: 16, nome: "Parana", arquivo: "/gpx/16-Parana.gpx", raioMetros: 1500 },
  { id: 17, nome: "Zita Vilela", arquivo: "", raioMetros: 1500 },
  {
    id: 18,
    nome: "Faz. Dinâmica",
    arquivo: "/gpx/pezao-e-dinamica.gpx",
    raioMetros: 1500,
  },
  { id: 19, nome: "Barra Norte", arquivo: "", raioMetros: 1500 },
  {
    id: 20,
    nome: "Chicao",
    arquivo: "/gpx/chicão.gpx",
    raioMetros: 1500,
  },
  {
    id: 21,
    nome: "Valmori e Martins",
    arquivo: "/gpx/valmor.gpx",
    raioMetros: 1500,
  },
  {
    id: 22,
    nome: "Jabuti",
    arquivo: "/gpx/jabuti.gpx",
    raioMetros: 1500,
  },
  {
    id: 23,
    nome: "Linha dos 40",
    arquivo: "/gpx/linha-40.gpx",
    raioMetros: 1500,
  },
  {
    id: 24,
    nome: "Bananal",
    arquivo: "",
    raioMetros: 1500,
  },
  {
    id: 25,
    nome: "Vicinal 2",
    arquivo: "/gpx/vicinal 2.gpx",
    raioMetros: 1500,
  },
  {
    id: 26,
    nome: "Gogó da Coruja",
    arquivo: "/gpx/gogo da coruja.gpx",
    raioMetros: 1500,
  },
];
